# Generated by Django 4.0.3 on 2022-04-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_faq_updated_by_alter_faq_created_by_inquiry_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='title',
            field=models.CharField(default='', max_length=80, verbose_name='질문 제목'),
            preserve_default=False,
        ),
    ]
