# Generated by Django 4.0.3 on 2022-05-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_inquiry_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('1', '문의 등록'), ('2', '접수 완료'), ('3', '답변 완료')], default='', max_length=5, verbose_name='질문 상태'),
            preserve_default=False,
        ),
    ]
